name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    name: build  # build+test on various versions of OCaml, on linux
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os:
            - ubuntu-latest
            - windows-latest
        ocaml-compiler:
            - '4.14'
            - '5.2'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install -t --deps-only benchmark
      - run: opam exec -- dune build --profile=release --force @install @runtest

